name: CI/CD
on: [push]

jobs:
  # Something with: buildx
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        run: |
              docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/thiesjoo/duodag:latest -t ghcr.io/thiesjoo/duodag:${GITHUB_REF##*/} --push .
