name: CI/CD
on: [push]
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
              docker build . -t ghcr.io/thiesjoo/duodag:latest -t ghcr.io/thiesjoo/duodag:${GITHUB_REF##*/}
              docker push ghcr.io/thiesjoo/duodag --all-tags